DefaultContentLanguage = "en"

[languages]
    [languages.en]
        title = "Michał K. Feiler, Informatics undergrad"
        baseURL = "https://a.archiet.pl/"
        weight = 1
    [languages.pl]
        baseURL = "https://o.archiet.pl/"
        title = "Michał K. Feiler, student I roku informatyki"
        weight = 2

[permalinks]
