[[redirects]]
from = "/"
to = "/index.:lang.html"
status = 200
query = {lang = ":lang"}

[[redirects]]
from = "/"
to = "/index.en.html"
status = 200

[[redirects]]
from = "/"
to = "/index.pl.html"
status = 200
conditions = {Language = ["pl"]}
