[build]
    publish = "target/"
    command = "./builder.py $SITELANG"

[[redirects]]
    from = "https://archiet.pl/*"
    to = "https://a.archiet.pl/:splat"
    force = true

[[redirects]]
    from = "http://archiet.pl/*"
    to = "http://a.archiet.pl/:splat"
    force = true

[[redirects]]
    from = "https://www.archiet.pl/*"
    to = "https://a.archiet.pl/:splat"
    force = true

[[redirects]]
    from = "http://www.archiet.pl/*"
    to = "http://a.archiet.pl/:splat"
    force = true