[[redirects]]
from = "/"
to = "/index.:lang.html"
status = 200
query = {lang = ":lang"}

[[redirects]]
from = "/"
to = "/index.:asklang.html"
status = 200
query = {asklang = ":asklang"}
headers = {Set-Cookie = "nf_lang=:asklang"}

[[redirects]]
from = "/"
to = "/index.pl.html"
status = 200
conditions = {Language = ["pl"]}

[[redirects]]
from = "/"
to = "/index.en.html"
status = 200
